#
# Makefile - WantJoin information tech co.ltd driver.
# Copyright(c) 2015, WantJoin information tech co.ltd.
#

#$(call all-subdir-src-or-makefile)
cflags-y += -D__BTREE2__ -D__ANDROID3__
obj-y += packflt/
